// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfPWeGmnTCWub6RS2oHh9KC6di7fijZc',
    appId: '1:222614531658:web:88f76cf75c0439662680b3',
    messagingSenderId: '222614531658',
    projectId: 'mynoter-pst220630',
    authDomain: 'mynoter-pst220630.firebaseapp.com',
    storageBucket: 'mynoter-pst220630.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpgG7rCVLbMAw6eFrhICrE22MdgXXZah0',
    appId: '1:222614531658:android:89eecae5466457e12680b3',
    messagingSenderId: '222614531658',
    projectId: 'mynoter-pst220630',
    storageBucket: 'mynoter-pst220630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_llnN9cOrKJcSF1YKsTmpPb11sNEtm04',
    appId: '1:222614531658:ios:842357c66667abe82680b3',
    messagingSenderId: '222614531658',
    projectId: 'mynoter-pst220630',
    storageBucket: 'mynoter-pst220630.appspot.com',
    iosClientId: '222614531658-ahltru5pnh7f1dbm7ssfbm4pa51ko90u.apps.googleusercontent.com',
    iosBundleId: 'hu.psteingart.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_llnN9cOrKJcSF1YKsTmpPb11sNEtm04',
    appId: '1:222614531658:ios:842357c66667abe82680b3',
    messagingSenderId: '222614531658',
    projectId: 'mynoter-pst220630',
    storageBucket: 'mynoter-pst220630.appspot.com',
    iosClientId: '222614531658-ahltru5pnh7f1dbm7ssfbm4pa51ko90u.apps.googleusercontent.com',
    iosBundleId: 'hu.psteingart.mynotes',
  );
}
